Repository ProyectoU8-Silabuz-BackEnd/health-tracker-backend, pull requests merged in 2023-01, with the labels that each got.

#8 create of model recordatory in schema.prisma
  prisma/schema.prisma
Labels: enhancement

#9 Feature 15 create component recordatory
  src/app.ts
  src/components/index.ts
  src/components/recordatory/controller.ts
  src/components/recordatory/index.ts
Labels: enhancement

#13 Develop
  prisma/schema.prisma
  src/app.ts
  src/components/index.ts
  src/components/medicacion/controller.ts
  src/components/medicacion/index.ts
Labels: feature

#16 Feature/component pastillas
  prisma/schema.prisma
  src/components/pastillas/controller.ts
Labels: feature

#20 Feature/router pastilla
  src/components/index.ts
  src/components/pastillas/index.ts
Labels: feature

#25 Feature 8 create component login
  package.json
  src/app.ts
  src/components/index.ts
  src/components/login/controller.ts
  src/components/login/index.ts
  src/middleware/auth/index.ts
  src/middleware/auth/strategies/jwt.ts
  src/middleware/auth/strategies/local.ts
  src/utils/auxiliar.user.ts
Labels: enhancement, feature
